version: '3.8'

services:
  deflock:
    image: public.ecr.aws/w2o0b9g0/deflock.me:latest
    expose:
      - 8080
    #restart: always
    stdin_open: true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - SSL_CERTIFICATE=/etc/letsencrypt/live/deflock.me/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/letsencrypt/live/deflock.me/privkey.pem
    restart: always
